# Generated by Django 5.1.2 on 2024-11-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('member', 'Member')], max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='members/%Y/%m')),
                ('designation', models.CharField(blank=True, max_length=250)),
                ('linkedin', models.URLField(blank=True, help_text='please use https:// before link')),
                ('github', models.URLField(blank=True, help_text='please use https:// before link')),
                ('facebook', models.URLField(blank=True, help_text='please use https:// before link')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order'], name='about_membe_order_85909c_idx')],
            },
        ),
    ]
