# Generated by Django 5.1.2 on 2024-11-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='portfolio/%Y/%m')),
                ('duration', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('link', models.URLField(blank=True, help_text='please use https:// before link')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order'], name='about_portf_order_b1918f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.CharField(max_length=10)),
                ('detail', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order'], name='about_proje_order_26fad8_idx')],
            },
        ),
    ]
