# Generated by Django 5.1.2 on 2024-11-09 04:36
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[], max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('salary_expectation', models.CharField(max_length=10)),
                ('cv', models.FileField(upload_to='cvs/%Y/%m')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='career_appl_created_a538e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time')], max_length=20)),
                ('job_mode', models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=20)),
                ('short_info', models.TextField()),
                ('deadline', models.DateField()),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'deadline'],
                'indexes': [models.Index(fields=['order'], name='career_job_order_2aaba9_idx')],
            },
        ),
    ]
