# Generated by Django 5.1.2 on 2024-11-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_job_job_mode_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='role',
            field=models.CharField(max_length=250),
        ),
    ]
