# Generated by Django 5.1.2 on 2024-11-09 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_alter_application_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='career_appl_created_a538e3_idx',
        ),
        migrations.RemoveField(
            model_name='application',
            name='created',
        ),
        migrations.AlterField(
            model_name='application',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='career.job'),
        ),
    ]
