# Generated by Django 5.1.2 on 2024-11-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='application',
            name='created',
            field=models.DateTimeField(blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(upload_to='cvs/%Y/%m'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-created'], name='career_appl_created_a538e3_idx'),
        ),
    ]
