# Generated by Django 5.1.2 on 2024-11-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_alter_application_options_application_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, upload_to='cvs/%Y/%m'),
        ),
    ]
