# Generated by Django 5.1.2 on 2024-11-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_alter_application_created_alter_application_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
