# Generated by Django 5.1.2 on 2024-11-05 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='service/%Y/%m')),
                ('home_icon', models.ImageField(blank=True, upload_to='service_icon/%Y/%m')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order'], name='loopers_ser_order_24e17a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField(default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='loopers.service')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order'], name='loopers_ser_order_db79f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='service/%Y/%m')),
                ('order', models.PositiveIntegerField(default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='loopers.service')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order'], name='loopers_sub_order_0dd5f5_idx')],
            },
        ),
    ]
