# Generated by Django 5.1.2 on 2024-11-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loopers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
