# Generated by Django 5.1.2 on 2024-11-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loopers', '0002_subservice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='slug',
            field=models.SlugField(blank=True, help_text='if does not fill automatically, keep blank', unique=True),
        ),
    ]
