# Generated by Django 5.1.2 on 2024-11-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loopers', '0003_alter_subservice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='slug',
            field=models.SlugField(blank=True, help_text='if does not fill automatically, leave blank'),
        ),
    ]
