# Generated by Django 5.1.2 on 2024-11-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loopers', '0004_alter_subservice_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='review/%Y/%m')),
                ('review', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order'], name='loopers_rev_order_a0e644_idx')],
            },
        ),
    ]
