# Generated by Django 5.1.2 on 2024-11-11 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loopers', '0006_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_range', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order'], name='loopers_pri_order_2936e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=250)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='loopers.pricing')),
            ],
        ),
    ]
