# Generated by Django 5.1.2 on 2024-11-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loopers', '0007_pricing_pricefeature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricefeature',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='pricefeature',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='pricefeature',
            index=models.Index(fields=['order'], name='loopers_pri_order_17ccc8_idx'),
        ),
    ]
